In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import os

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
data = pd.read_csv("/content/iris.data")
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [49]:
data.columns = ["sl","sw","pl","pw","target"]
data.head()

sl   sw   pl   pw       target
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [50]:
data["target"].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: target, dtype: int64

In [51]:
X = data.drop(["target"],axis=1)
X.head()

sl   sw   pl   pw
0  4.9  3.0  1.4  0.2
1  4.7  3.2  1.3  0.2
2  4.6  3.1  1.5  0.2
3  5.0  3.6  1.4  0.2
4  5.4  3.9  1.7  0.4

In [64]:
from sklearn.preprocessing import LabelEncoder

In [66]:
le = LabelEncoder()
data['target'] = le.fit_transform(data['target'])
y = data['target'].values

In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [68]:
X_train.shape

(119, 4)

In [69]:
X_test.shape

(30, 4)

In [113]:
from keras.models import Sequential
from keras.layers import Dense,Dropout


In [114]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(8, input_dim=4, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

In [115]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [116]:
history = model.fit(X_train, y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 1s 5ms/step - loss: 2.6192 - accuracy: 0.0000e+00
Epoch 2/20
4/4 [==============================] - 0s 4ms/step - loss: 2.5351 - accuracy: 0.0000e+00
Epoch 3/20
4/4 [==============================] - 0s 4ms/step - loss: 2.4443 - accuracy: 0.0084
Epoch 4/20
4/4 [==============================] - 0s 4ms/step - loss: 2.3613 - accuracy: 0.0084
Epoch 5/20
4/4 [==============================] - 0s 4ms/step - loss: 2.2847 - accuracy: 0.0168
Epoch 6/20
4/4 [==============================] - 0s 4ms/step - loss: 2.2111 - accuracy: 0.0504
Epoch 7/20
4/4 [==============================] - 0s 4ms/step - loss: 2.1423 - accuracy: 0.1261
Epoch 8/20
4/4 [==============================] - 0s 4ms/step - loss: 2.0768 - accuracy: 0.1765
Epoch 9/20
4/4 [==============================] - 0s 4ms/step - loss: 2.0166 - accuracy: 0.2101
Epoch 10/20
4/4 [==============================] - 0s 4ms/step - loss: 1.9676 - accuracy: 0.2605
Epoch 11/20
4/4 [==============

In [117]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 122ms/step - loss: 1.7273 - accuracy: 0.3000


[1.7272616624832153, 0.30000001192092896]

In [118]:
pred=model.predict(X_test[:10])
print(pred)

1/1 [==============================] - 0s 45ms/step
[[0.44334772 0.40885535 0.14779687]
 [0.07542306 0.19239347 0.73218346]
 [0.41197494 0.4123786  0.17564647]
 [0.3243165  0.38830912 0.2873744 ]
 [0.34606692 0.39706618 0.25686687]
 [0.4218212  0.41394293 0.1642358 ]
 [0.0947173  0.21265614 0.69262654]
 [0.0813517  0.19549969 0.72314864]
 [0.36235934 0.4165575  0.22108318]
 [0.31728703 0.38868463 0.29402837]]


In [119]:
from sklearn.metrics import accuracy_score
y_pred = np.argmax(model.predict(X_test), axis=1)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

1/1 [==============================] - 0s 27ms/step
Accuracy: 0.3


In [120]:
scores = model.evaluate(X_train,y_train)
print("Training Accuracy: %.2f%%\n" % (scores[1]*100))
scores = model.evaluate(X_test,y_test)
print("Testing Accuracy: %.2f%%\n" % (scores[1]*100))

4/4 [==============================] - 0s 4ms/step - loss: 1.6512 - accuracy: 0.3277
Training Accuracy: 32.77%

1/1 [==============================] - 0s 25ms/step - loss: 1.7273 - accuracy: 0.3000
Testing Accuracy: 30.00%



In [121]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_dim=4, activation='relu'),
    tf.keras.layers.Dense(28, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

In [122]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [123]:
history = model.fit(X_train, y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 1s 6ms/step - loss: 1.2177 - accuracy: 0.3782
Epoch 2/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0459 - accuracy: 0.4034
Epoch 3/20
4/4 [==============================] - 0s 5ms/step - loss: 0.9816 - accuracy: 0.6555
Epoch 4/20
4/4 [==============================] - 0s 5ms/step - loss: 0.9294 - accuracy: 0.6639
Epoch 5/20
4/4 [==============================] - 0s 5ms/step - loss: 0.8910 - accuracy: 0.8319
Epoch 6/20
4/4 [==============================] - 0s 6ms/step - loss: 0.8547 - accuracy: 0.7647
Epoch 7/20
4/4 [==============================] - 0s 5ms/step - loss: 0.8159 - accuracy: 0.8739
Epoch 8/20
4/4 [==============================] - 0s 5ms/step - loss: 0.7753 - accuracy: 0.8151
Epoch 9/20
4/4 [==============================] - 0s 6ms/step - loss: 0.7334 - accuracy: 0.7731
Epoch 10/20
4/4 [==============================] - 0s 6ms/step - loss: 0.6896 - accuracy: 0.8739
Epoch 11/20
4/4 [======================

In [124]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 197ms/step - loss: 0.3969 - accuracy: 1.0000


[0.3969303071498871, 1.0]

In [125]:
scores = model.evaluate(X_train,y_train)
print("Training Accuracy: %.2f%%\n" % (scores[1]*100))
scores = model.evaluate(X_test,y_test)
print("Testing Accuracy: %.2f%%\n" % (scores[1]*100))

4/4 [==============================] - 0s 5ms/step - loss: 0.4284 - accuracy: 0.9664
Training Accuracy: 96.64%

1/1 [==============================] - 0s 32ms/step - loss: 0.3969 - accuracy: 1.0000
Testing Accuracy: 100.00%



In [126]:
history = model.fit(X_train, y_train,validation_split = 0.1,
                    epochs=10, batch_size=32)

Epoch 1/10
4/4 [==============================] - 0s 42ms/step - loss: 0.4278 - accuracy: 0.9720 - val_loss: 0.3860 - val_accuracy: 1.0000
Epoch 2/10
4/4 [==============================] - 0s 23ms/step - loss: 0.4155 - accuracy: 0.9626 - val_loss: 0.3697 - val_accuracy: 1.0000
Epoch 3/10
4/4 [==============================] - 0s 23ms/step - loss: 0.4001 - accuracy: 0.9720 - val_loss: 0.3506 - val_accuracy: 1.0000
Epoch 4/10
4/4 [==============================] - 0s 16ms/step - loss: 0.3856 - accuracy: 0.9720 - val_loss: 0.3339 - val_accuracy: 0.9167
Epoch 5/10
4/4 [==============================] - 0s 15ms/step - loss: 0.3738 - accuracy: 0.9720 - val_loss: 0.3195 - val_accuracy: 0.9167
Epoch 6/10
4/4 [==============================] - 0s 23ms/step - loss: 0.3670 - accuracy: 0.9720 - val_loss: 0.3144 - val_accuracy: 1.0000
Epoch 7/10
4/4 [==============================] - 0s 21ms/step - loss: 0.3494 - accuracy: 0.9720 - val_loss: 0.2970 - val_accuracy: 0.9167
Epoch 8/10
4/4 [===========

In [127]:
scores = model.evaluate(X_train,y_train)
print("Training Accuracy: %.2f%%\n" % (scores[1]*100))
scores = model.evaluate(X_test,y_test)
print("Testing Accuracy: %.2f%%\n" % (scores[1]*100))

4/4 [==============================] - 0s 6ms/step - loss: 0.3149 - accuracy: 0.9580
Training Accuracy: 95.80%

1/1 [==============================] - 0s 38ms/step - loss: 0.3024 - accuracy: 0.9333
Testing Accuracy: 93.33%



In [128]:
checkpoint_path = "/content/drive/MyDrive/checkpoints/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 monitor='val_loss',
                                                 verbose=1,
                                                 save_best_only=True)


In [129]:
model.fit(X_train,
          y_train,
          epochs=50,
          validation_split = 0.1,
#        validation_data=(X_test, y_test),
          callbacks=[cp_callback])

Epoch 1/50
1/4 [======>.......................] - ETA: 0s - loss: 0.3587 - accuracy: 0.9375
Epoch 1: val_loss improved from inf to 0.25805, saving model to /content/drive/MyDrive/checkpoints/cp.ckpt
4/4 [==============================] - 0s 54ms/step - loss: 0.3147 - accuracy: 0.9626 - val_loss: 0.2580 - val_accuracy: 0.9167
Epoch 2/50
1/4 [======>.......................] - ETA: 0s - loss: 0.3136 - accuracy: 0.9375
Epoch 2: val_loss improved from 0.25805 to 0.24974, saving model to /content/drive/MyDrive/checkpoints/cp.ckpt
4/4 [==============================] - 0s 32ms/step - loss: 0.3030 - accuracy: 0.9720 - val_loss: 0.2497 - val_accuracy: 0.9167
Epoch 3/50
1/4 [======>.......................] - ETA: 0s - loss: 0.2835 - accuracy: 1.0000
Epoch 3: val_loss improved from 0.24974 to 0.24334, saving model to /content/drive/MyDrive/checkpoints/cp.ckpt
4/4 [==============================] - 0s 25ms/step - loss: 0.2955 - accuracy: 0.9720 - val_loss: 0.2433 - val_accuracy: 1.0000
Epoch 4/50


In [130]:
scores = model.evaluate(X_train,y_train)
print("Training Accuracy: %.2f%%\n" % (scores[1]*100))
scores = model.evaluate(X_test,y_test)
print("Testing Accuracy: %.2f%%\n" % (scores[1]*100))

4/4 [==============================] - 0s 4ms/step - loss: 0.1123 - accuracy: 0.9832
Training Accuracy: 98.32%

1/1 [==============================] - 0s 25ms/step - loss: 0.1096 - accuracy: 0.9333
Testing Accuracy: 93.33%



In [131]:
model.load_weights(checkpoint_path)

In [132]:
scores = model.evaluate(X_train,y_train)
print("Training Accuracy: %.2f%%\n" % (scores[1]*100))
scores = model.evaluate(X_test,y_test)
print("Testing Accuracy: %.2f%%\n" % (scores[1]*100))

4/4 [==============================] - 0s 4ms/step - loss: 0.1123 - accuracy: 0.9832
Training Accuracy: 98.32%

1/1 [==============================] - 0s 25ms/step - loss: 0.1096 - accuracy: 0.9333
Testing Accuracy: 93.33%



In [134]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_dim=4, activation='relu'),
    tf.keras.layers.Dense(28, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(3, activation='softmax')
])


In [140]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
history=model.fit(X_train, y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 3s 13ms/step - loss: 0.5495 - accuracy: 0.7983
Epoch 2/20
4/4 [==============================] - 0s 8ms/step - loss: 0.5286 - accuracy: 0.7731
Epoch 3/20
4/4 [==============================] - 0s 8ms/step - loss: 0.5114 - accuracy: 0.8151
Epoch 4/20
4/4 [==============================] - 0s 7ms/step - loss: 0.4581 - accuracy: 0.7983
Epoch 5/20
4/4 [==============================] - 0s 7ms/step - loss: 0.4431 - accuracy: 0.8403
Epoch 6/20
4/4 [==============================] - 0s 14ms/step - loss: 0.4631 - accuracy: 0.8067
Epoch 7/20
4/4 [==============================] - 0s 8ms/step - loss: 0.4749 - accuracy: 0.7899
Epoch 8/20
4/4 [==============================] - 0s 7ms/step - loss: 0.4881 - accuracy: 0.7899
Epoch 9/20
4/4 [==============================] - 0s 5ms/step - loss: 0.4603 - accuracy: 0.7563
Epoch 10/20
4/4 [==============================] - 0s 5ms/step - loss: 0.4268 - accuracy: 0.8151
Epoch 11/20
4/4 [====================

In [141]:
scores = model.evaluate(X_train,y_train)
print("Training Accuracy: %.2f%%\n" % (scores[1]*100))
scores = model.evaluate(X_test,y_test)
print("Testing Accuracy: %.2f%%\n" % (scores[1]*100))

4/4 [==============================] - 0s 9ms/step - loss: 0.2895 - accuracy: 0.9580
Training Accuracy: 95.80%

1/1 [==============================] - 0s 77ms/step - loss: 0.2633 - accuracy: 1.0000
Testing Accuracy: 100.00%

